Add Turso Database (#3)
* Add turso base config

* Add turso workflows

* Update turso prev workflow

* Add missing auth_token to workflow

* update db migrations

diff --git a/.github/workflows/deploy-preview.yml b/.github/workflows/deploy-preview.yml
--- a/.github/workflows/deploy-preview.yml
+++ b/.github/workflows/deploy-preview.yml
@@ -2,9 +2,6 @@ name: Preview Deployment
 on: [pull_request]
 
 env:
-  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
-  NEON_USERNAME: ${{ secrets.NEON_USERNAME }}
-  NEON_DB_NAME: ${{ secrets.NEON_DB_NAME }}
   CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
   CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
@@ -32,26 +29,40 @@ jobs:
         id: branch-name
         uses: tj-actions/branch-names@v8
 
-      - id: create-branch
-        name: Create Neon Database Branch
-        uses: neondatabase/create-branch-action@v5
-        with:
-          project_id: ${{ secrets.NEON_PROJECT_ID }}
-          username: ${{ secrets.NEON_USERNAME }}
-          branch_name: preview/${{ steps.branch-name.outputs.current_branch }}
-          api_key: ${{ secrets.NEON_API_KEY }}
-          database: ${{ secrets.NEON_DB_NAME }}
+      - name: Create Turso Database Branch
+        id: create-db
+        shell: bash
+        run: |
+          RESPONSE=$(curl -X POST \
+          -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -d '{"name": "preview-${{ github.sha }}", "group": "default", "seed": {"type": "database", "name": "${{ secrets.TURSO_DATABASE_NAME }}"} }' \
+          "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases")
+
+          if [ $? -ne 0 ]; then
+            echo "API call failed"
+            exit 1
+          fi
+
+          HOSTNAME=$(echo $RESPONSE | jq -r '.database.Hostname')
+          if [ -z "$HOSTNAME" ]; then
+            echo "Hostname not found in response"
+            exit 1
+          fi
+
+          echo "Extracted hostname: $HOSTNAME"
+          echo "hostname=libsql://$HOSTNAME" >> $GITHUB_OUTPUT
 
       - name: Build
         run: pnpm run build
         env:
-          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
+          TURSO_DB_URL: ${{ steps.create-db.outputs.hostname }}
 
-      - name: Run Migrations
+      - name: Apply Database Migrations
         run: pnpm run db:migrate
         env:
-          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
-          DIRECT_DB_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
+          TURSO_DB_URL: ${{ steps.create-db.outputs.hostname }}
+          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
 
       - name: Deploy to Workers Preview
         uses: cloudflare/wrangler-action@v3
@@ -62,9 +73,11 @@ jobs:
           command: deploy --env preview
           environment: preview
           secrets: |
-            DATABASE_URL
+            TURSO_DB_URL
+            TURSO_AUTH_TOKEN
         env:
-          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
+          TURSO_DB_URL: ${{ steps.create-db.outputs.hostname }}
+          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
 
       - name: Extract Version ID
         id: version
@@ -80,4 +93,4 @@ jobs:
             🚀 Preview deployment is ready!
 
             Worker Preview URL: https://${{ steps.version.outputs.version_id }}-gingga-preview.jsegoviadev.workers.dev
-            Neon Database Branch: https://console.neon.tech/app/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ steps.create-branch.outputs.branch_id }}
+            Turso Database Branch: https://app.turso.tech/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/preview-${{ github.sha }}
